### ISSUE TITLE
Add support for access and volume mode in storage mapping

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/forklift-controller#77]
When a storage mapping is created, the only information we have is the destination storage class name. However, this is not sufficient, because some access modes and volume modes are not support by Kubevirt, e.g. Ceph + Filesystem or Cinder + RWX. So, we shouldn't allow unsupported access and volume modes.

The idea is to implement a storage support matrix that would be used to validate access and volume modes for the destination storage classes, as well as provide _intelligent_ default values for each provisioner type. The support matrix would be stored in a Config Map managed by the operator and mounted in the controller and UI pods.

The access modes are documented in [Kubernetes > Persistent Volumes > Access Modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes).
The volumes modes are documented in [Kubernetes > Persistent Volumes > Volume Modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-modes).
The list of provisioners that support block mode is available in [Kubernetes > Persistent Volumes > Raw Block Volume Support](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support).

A possible format for the support matrix is:

```yaml
---
- kubevirt_version: v2.5.0
  supported_storages:
  - provisioner_name: kubernetes.io/aws-ebs
    access_modes:
    - ReadWriteOnce
    volume_modes:
    - Block
    - Filesystem
  - provisioner_name: kubernetes.io/rbd
    access_modes:
    - ReadWriteOnce
    - ReadOnlyMany
    volume_modes:
    - Block
    - Filesystem
  - provisioner_name: kubernetes.io/glusterfs
    access_modes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
    volume_modes:
    - Filesystem
```

**Comment by jortel** [comment]
Recommend:
```
---
- kubevirtVersion: v2.5.0
  provisioners:
  - name: kubernetes.io/aws-ebs
    accessModes:
    - ReadWriteOnce
    volumeModes:
    - Block
    - Filesystem
 ```

**Comment by mansam** [comment]
VMIO currently supports setting the volume mode on the Storage and Disk mappings, and I'm working on support for setting the access mode.

```go
// StorageResourceMappingItem defines the storage mapping of a single resource from the provider to kubevirt
// +k8s:openapi-gen=true
type StorageResourceMappingItem struct {
	Source Source           `json:"source"`
	Target ObjectIdentifier `json:"target"`

	// +optional
	VolumeMode *corev1.PersistentVolumeMode `json:"volumeMode,omitempty"`
	// +optional
	AccessMode *corev1.PersistentVolumeAccessMode `json:"accessMode,omitempty"`
}
```

**Comment by mansam** [comment]
https://github.com/kubevirt/vm-import-operator/pull/438

**Comment by fdupont-redhat** [comment]
@jortel, proposing the following format:

```
---
- kubevirtVersion: v2.5.0
  provisioners:
  - name: kubernetes.io/rbd
    modes:
    - volumeMode: Block
      accessModes:
      - ReadWriteOnce
    - volumeMode: Filesystem
      accessModes:
      - ReadWriteMany
      - ReadWriteOnce
```

You can see that Ceph-RBD doesn't support ReadWriteMany when volume mode is Block, while it supports it when volume mode is Filesystem. I named the fields `modes`, but if you have something better, I'll follow.

**Comment by jortel** [comment]
Rather than a yaml matrix file, I think separate _(new)_ CRs for each provisioner may be more idiomatic for k8s.  I discussed with @shawn-hurley and he agreed.  The operator would install these CRs for the appropriate version of k8s.  The user would e free to add/update/delete.

Perhaps something like:
```
---
apiVersion: forklift.konveyor.io/v1alpha1
kind: Provisioner
metadata:
  name: rbd
  namespace: openshift-migration
spec:
  - name: kubernetes.io/rbd
    features:
    - SmartCloning
    - Snapshots
    volumeModes:
    - name: Block
      features: []
      accessModes:
      - name: ReadWriteOnce
        features: []
    - name: Filesystem
      features: []
      accessModes:
      - name: ReadWriteMany
        features:
        - LiveMigration
      - name: ReadWriteOnce
        features: []
```

@fdupont-redhat Thoughts?
